name: cruky
description: A sample command-line application.
version: 0.13.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  path: ^1.8.1
  meta: ^1.8.0
  mime: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
