name: croky
description: croky is server-side library to create API with modern and fast performance.
version: 0.0.1
homepage: https://github.com/seifalmotaz/croky
repository: https://github.com/seifalmotaz/croky
documentation: https://seifalmotaz.github.io/croky

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  path: ^1.8.1
  meta: ^1.8.0
  mime: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
